### ISSUE TITLE
Default values not provided for REDIS_DEFAULT_TTL_MS in the sample.env

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#1348]
### Problem

The instructions don't mention to update this config in the .env in notifications and api. This was identified when running docker compose up and viewing the error. Once these configs were set with the value the error was resolved. 

```
notifications-1  | [Nest] 34  - 12/13/2024, 1:51:36 AM   ERROR [ExceptionHandler] Config validation error: "REDIS_DEFAULT_TTL_MS" must be a number
notifications-1  | Error: Config validation error: "REDIS_DEFAULT_TTL_MS" must be a number
notifications-1  |     at ConfigModule.forRoot (/usr/src/app/node_modules/.pnpm/@nestjs+config@3.3.0_@nestjs+common@10.4.5_class-transformer@0.5.1_class-validator@0.14.1_ref_y4h4zffot46cgzyedcwdfu7yba/node_modules/@nestjs/config/dist/config.module.js:86:23)
notifications-1  |     at ./apps/notifications/src/notifications.module.ts (/usr/src/app/dist/apps/notifications/main.js:19308:40)
notifications-1  |     at __webpack_require__ (/usr/src/app/dist/apps/notifications/main.js:40914:42)
notifications-1  |     at /usr/src/app/dist/apps/notifications/main.js:40962:32
notifications-1  |     at /usr/src/app/dist/apps/notifications/main.js:40973:3
notifications-1  |     at Object.<anonymous> (/usr/src/app/dist/apps/notifications/main.js:40975:12)
notifications-1  |     at Module._compile (node:internal/modules/cjs/loader:1546:14)
notifications-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
notifications-1  |     at Module.load (node:internal/modules/cjs/loader:1317:32)
notifications-1  |     at Module._load (node:internal/modules/cjs/loader:1127:12)
```

### Solution

Defaults should be provided in the .env so that it works as expected.

**Comment by SvetBorislavov** [comment]
Fixed in #1345
