### ISSUE TITLE
Error when using `docker compose up`

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#944]
### Problem

When I run the backend locally using docker compose up for the app the logs show this error. Not sure why or how to resolve. It doesn't block me from enabling the app in dev mode but would still like to log it here so it can be addressed.

```
notifications-1  | [23:20:16.811] INFO (34): Nest application successfully started {"context":"NestApplication"}
api-1            | Error: ENOENT: no such file or directory, open '/usr/src/app/cert/key.pem'
api-1            |     at Object.openSync (node:fs:561:18)
api-1            |     at Object.readFileSync (node:fs:445:35)
api-1            |     at createAppForDevelopment (/usr/src/app/dist/apps/api/main.js:19629:24)
api-1            |     at createApp (/usr/src/app/dist/apps/api/main.js:19618:22)
api-1            |     at bootstrap (/usr/src/app/dist/apps/api/main.js:19606:23)
api-1            |     at /usr/src/app/dist/apps/api/main.js:19638:1
api-1            |     at /usr/src/app/dist/apps/api/main.js:19640:3
api-1            |     at Object.<anonymous> (/usr/src/app/dist/apps/api/main.js:19642:12)
api-1            |     at Module._compile (node:internal/modules/cjs/loader:1546:14)
api-1            |     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10) {
api-1            |   errno: -2,
api-1            |   code: 'ENOENT',
api-1            |   syscall: 'open',
api-1            |   path: '/usr/src/app/cert/key.pem'
api-1            | }

```

### Solution

see above

**Comment by SvetBorislavov** [comment]
Following the instructions will resolve the problem describe above
